### PR TITLE
SWS-286 Make Service Health donut as a separate component

### PR DESCRIPTION
**Pull request by jotak**
- Remove from Service Metrics
- Add to Service Details

Health donut

### CODE REVIEW

**Comment by jotak** [comment]
@lucasponce / @xeviknal / @abonas what do you think about the layout?

**Comment by lucasponce** [comment]
> what do you think about the layout?

I think in terms of space, health can be smaller and be shown in the service description card.
I personally don't think it deserves a specific card for it.

Potential suggestions, would be to use a smaller graph and use the initial title, like:
image

Or similar, UX discussions can go anywhere, but I guess it would make sense to optimize space there.

**Comment by jotak** [comment]
With some tweaking I can have a result like this:

health

To be honest I'm not really convinced. We can make it appear smaller, or even text-based, without putting it at an unusual place.

Would it make sense to have it in the "deployments" card? Since it's actually an information about the deployments.
We already have `Pod status: 1/1` there. We could change that to `Deployed pods: 1/1` and below `Pods health: 1/1` ?

**Comment by lucasponce** [comment]
> Would it make sense to have it in the "deployments" card? Since it's actually an information about the deployments.

That sounds good to me as well.
Or just to put in in the description, right to Endpoints, as it is info for the whole service, I guess.
Also, it has space there and probably visally it's similar.

**Comment by pilhuhn** [comment]
The small one in the top right corner looks odd to me.
Patternfly already has this type of card where you have a donut and some details below
http://www.patternfly.org/pattern-library/cards/utilization-trend-card/#card-with-a-single-metric
(we would not show the sparkline).
If I understand correctly, the health and the pod-status 1/1 are the same thing, so that would match.

**Comment by jotak** [comment]
@pilhuhn they are not the same thing: if i understand correctly pods status comes from k8s deployment status. Health come from envoy metrics. They may not be always identical, for instance when a pod is up but badly performing it might be excluded from envoy cluster, so it's still deployed but will be marked as unhealthy.

**Comment by xeviknal** [comment]
@jotak good point, I was about to ask you for that.
Then, I am up to add this donut next to endpoints column, not as a different card/box, but as a normal column.

**Comment by pilhuhn** [comment]
On 21 Mar 2018, at 11:43, Joel Takvorian wrote:

> performing it might be excluded from envoy cluster, so it's still 
> deployed but will be marked as unhealthy.

Right. So in this case (if istio is not deciding to kill the entire 
pod),
we need to re-think those two classes of "health", and make the
final health dependent on both.

And then I have the impression that we need to revisit the entire notion
of "health" in a later stage when it is possible to also derive it from
different sources. E.g. if there are 10 pods for a service and 1 is slow
and there is low traffic, I'd not say the app is unhealthy or degraded

-- 
hwr@pilhuhn.de  m:0179/207 4919  b:http://pilhuhn.blogspot.com

**Comment by jotak** [comment]
Proposal with smaller donut and included in main card:

donut

@pilhuhn I agree that we must define what exactly is health. For now I'm just taking the istio definition which itself is based on envoy's.

**Comment by lucasponce** [comment]
> Proposal with smaller donut and included in main card:

I like this alternative, it looks more in line with the elements of the service details page.

**Comment by jotak** [comment]
I rebased and push the last proposed alternative

**Pull request merged**
