### PR TITLE
fix behavior of loading graphs

### PR DESCRIPTION
**Pull request by jmazzitelli**
- add loading state where needed
- show loading message when downloading the data
- don't use larger fonts - use standard font size

### CODE REVIEW

**Comment by pilhuhn** [comment]
Some smaller issues: for groups, the 2nd sparkline is out of the container.
bildschirmfoto 2018-03-21 um 16 46 32

For single nodes, there is an additional ; 
bildschirmfoto 2018-03-21 um 16 46 46

And I think the 'Err' is too close to the % (?)

**Comment by jmazzitelli** [comment]
I fixed the semicolon - that was just a typo. That's gone now.

As for the graphs outside the container, I do not see that. I assume it has to do with screen size/resolution. We do plan on working on better look-n-feel issues like this later.

**Comment by pilhuhn** [comment]
Yes it has to do with the resolution. But it is also that the containers behave differently

**Comment by israel-hdez** [comment]
@pilhuhn I think I have fixed the issue about the graphs out of the container. I'll push the fix in another PR.

**Pull request merged**
