### PR TITLE
title "Ip" looks better when it is in upper case "IP"

### PR DESCRIPTION
**Pull request by jkandasa**

### CODE REVIEW

**Comment by abonas** [comment]
@jkandasa please check the test failures.
other than that +1 on the change from me

**Comment by rhqci** [comment]
Can one of the admins verify this patch?

**Comment by jotak** [comment]
The snapshot test fails which is expected for this change, @jkandasa you just just have to delete the snapshot (I think it's this one: `src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoDescription.test.tsxsrc/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoDescription.test.tsx`) then run `npm test` and commit with the updated snapshot.

**Comment by jkandasa** [comment]
@abonas @jotak Thank you! Updated the snapshot file.

**Pull request merged**
