### PR TITLE
SWS-259 add tests to ServiceDetailInfo

### PR DESCRIPTION
**Pull request by aljesusg**
Jira [SWS-259](https://issues.jboss.org/browse/SWS-259)

reviews

@vnugent Here is the WIP of tests about ServiceDetail Info, It's working with snaphots !!! Thanks

_Changed dependencies model by Backend now the json is a Map<string,string[]>_

### CODE REVIEW

**Comment by jotak** [comment]
Hey, a personal question about using snapshots. I understand it's an easy way to test. But since it doesn't enforce any specific criteria for matching that is written in test, I'm wondering how confident we can be, when the snapshot doesn't match because we changed something intentionally, in that the new snapshot if correct? (if you see what I mean)

**Comment by jotak** [comment]
ok, self-answering, the snapshot is of course commited so author and reviewers can check if changes are suspicious.

**Comment by xeviknal** [comment]
Perhaps it will be good to have one reviewer from QE. Perhaps @vnugent can have a look into it?

**Comment by vnugent** [comment]
Tests look good. Since `ServiceInfoBadge` renders a lot of text so it's a good candidate for snapshot test. Generally we may want to wait a bit on writing snapshot tests until the UI is more hashed out.

**Pull request merged**
